---
- name: cart set up
  hosts: cart
  become: yes
  tasks:
  - name: Disable and enable Node.js module via dnf
    ansible.builtin.shell: |
     dnf module disable nodejs -y
     dnf module enable nodejs:18 -y
   
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create roboshop user
    ansible.builtin.user:
      name: roboshop
  
  - name: Recursively remove app director
    ansible.builtin.file:
      path: /app
      state: absent


  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download cart app code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: Unzip the application contents into /app
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app


  - name: copy cart.service into systemd
    copy:
      src: /home/centos/rs_ansible/cart.service
      dest: /etc/systemd/system/cart.service
      

  - name: daemon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true


  

  - name: restart and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes