---
- name: catalogue set up
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable and enable Node.js module via dnf
    ansible.builtin.shell: |
     dnf module disable nodejs -y
     dnf module enable nodejs:18 -y
   
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue app code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Unzip the application contents into /app
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes