---
- name: user set up
  hosts: user
  become: yes
  tasks:
  - name: Disable and enable Node.js module via dnf
    ansible.builtin.shell: |
     dnf module disable nodejs -y
     dnf module enable nodejs:18 -y
   
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create roboshop user
    ansible.builtin.user:
      name: roboshop
  
  - name: Recursively remove app director
    ansible.builtin.file:
      path: /app
      state: absent


  - name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download user app code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: Unzip the application contents into /app
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app


  - name: copy user.service into systemd
    copy:
      src: /home/centos/rs_ansible/user.service
      dest: /etc/systemd/system/user.service
      

  - name: daemon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true



  - name: copy mongo repo into /etc/yum.repos.d/mongo.repo
    copy:
      src: /home/centos/rs_ansible/mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
      

  - name: Checking the products count
    ansible.builtin.command: mongo --host mongodb.roboriya.shop --quiet --eval 'db = db.getSiblingDB("user"), db.user.count()'
    register: user_count

  - name: printing the count
    ansible.builtin.debug:
      msg: "user_count: {{product_count}}"

  - name: load the user data
    ansible.builtin.command: mongo --host mongodb.roboriya.shop < /app/schema/user.js
    when: user_count.stdout == '0'

  - name: restart and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes